/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishedDate' : IDL.Int,
  'published' : IDL.Bool,
  'tags' : IDL.Vec(IDL.Text),
  'summary' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'viewPassword' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'githubUrl' : IDL.Text,
  'imageUrl' : IDL.Text,
  'demoUrl' : IDL.Text,
  'techStack' : IDL.Vec(IDL.Text),
  'demoPassword' : IDL.Opt(IDL.Text),
});
export const Skill = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'proficiency' : IDL.Nat,
  'category' : IDL.Text,
});
export const AboutSection = IDL.Record({
  'title' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'profileImageUrl' : IDL.Text,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func([BlogPost], [], []),
  'createProject' : IDL.Func([Project], [], []),
  'createSkill' : IDL.Func([Skill], [], []),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deleteContactMessage' : IDL.Func([IDL.Text], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'deleteSkill' : IDL.Func([IDL.Text], [], []),
  'getAboutSection' : IDL.Func([], [AboutSection], ['query']),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Text], [BlogPost], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactMessage' : IDL.Func([ContactMessage], [], []),
  'updateAboutSection' : IDL.Func([AboutSection], [], []),
  'updateBlogPost' : IDL.Func([BlogPost], [], []),
  'updateProject' : IDL.Func([Project], [], []),
  'updateSkill' : IDL.Func([Skill], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishedDate' : IDL.Int,
    'published' : IDL.Bool,
    'tags' : IDL.Vec(IDL.Text),
    'summary' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'viewPassword' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'githubUrl' : IDL.Text,
    'imageUrl' : IDL.Text,
    'demoUrl' : IDL.Text,
    'techStack' : IDL.Vec(IDL.Text),
    'demoPassword' : IDL.Opt(IDL.Text),
  });
  const Skill = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'proficiency' : IDL.Nat,
    'category' : IDL.Text,
  });
  const AboutSection = IDL.Record({
    'title' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'profileImageUrl' : IDL.Text,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func([BlogPost], [], []),
    'createProject' : IDL.Func([Project], [], []),
    'createSkill' : IDL.Func([Skill], [], []),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deleteContactMessage' : IDL.Func([IDL.Text], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'deleteSkill' : IDL.Func([IDL.Text], [], []),
    'getAboutSection' : IDL.Func([], [AboutSection], ['query']),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
    'getBlogPost' : IDL.Func([IDL.Text], [BlogPost], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func([IDL.Text], [Project], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactMessage' : IDL.Func([ContactMessage], [], []),
    'updateAboutSection' : IDL.Func([AboutSection], [], []),
    'updateBlogPost' : IDL.Func([BlogPost], [], []),
    'updateProject' : IDL.Func([Project], [], []),
    'updateSkill' : IDL.Func([Skill], [], []),
  });
};

export const init = ({ IDL }) => { return []; };